### ISSUE TITLE
test data for di_tads.10k.2M/define_boundary_by_DI_delta.r

### ISSUE THREAD

**Issue by liufuyan2016** [shawnzhangyx/cvdc_scripts#1]
Hi, Thanks for your effort fot Hi-C analysis. Recently ,I want to use these scripts for our study. However ,I could not known the input format for "di_tads.10k.2M/define_boundary_by_DI_delta.r",Could you provide an test data(e-mail :liufuyan2011@126.com) or each column required? Thank you!

**Comment by shawnzhangyx** [comment]
@liufuyan2016 Here is some test data for this script: 
[test_data.txt](https://github.com/shawnzhangyx/cvdc_scripts/files/2700072/test_data.txt)
The DI delta score was calculated by the `di_tads.10k.2M/calc_DI_delta.r` script. And you could find the input for this script in the `di_tads.10.2M/master.sh`. Basically, the original input files you need is the boundaries and the DI bedgraph files. Please let me know if you have any additional questions.

**Comment by liufuyan2016** [comment]
Thanks for your reply! I also have a question about the "find_dynamic_boundary_DI_delta.r". How to output fdr value for each boundary?

**Comment by liufuyan2016** [comment]
another question is :how to output fdr for each booundary?

**Comment by shawnzhangyx** [comment]
@liufuyan2016 You could add the FDR values as an additional column to the original table and output it. It should be fairly easy to do in R.
