### ISSUE TITLE
post_process_loops.sh script input?

### ISSUE THREAD

**Issue by liufuyan2016** [shawnzhangyx/cvdc_scripts#2]
The script is below:
for sample in $(cat ../../data/hic/meta/names.txt); do
  (
  for chr in {1..22} X; do 
    echo $sample $chr
    Rscript remove_pixel_wo_nearby.r ../../analysis/customLoops/tests_sample_chr/chr${chr}.${sample}.txt 
    Rscript colapse_pixels.r ../../analysis/customLoops/tests_sample_chr/chr${chr}.${sample}.txt.removed 
  done
  ) &
  done

Could you help me how to produce the ../../analysis/customLoops/tests_sample_chr/chr${chr}.${sample}.txt  file? Thank ypou very much!

**Comment by shawnzhangyx** [comment]
I'm sorry that part wasn't very clear in the scripts. 
The script to produce the files are here: 
`Rscript ../../scripts/customLoops/test.main.r ../../data/hic/matrix_raw/$name/${chr}_10000.txt tests_sample_chr/chr${chr}.$name.txt ../../data/hic/matrix/$name/${chr}_10000.txt
`
The test_main.r file are in the same folder. The inputs are raw and normalized matrices from juicebox.

**Comment by liufuyan2016** [comment]
Thank you for reply!After run the post_process_loops.sh script and which next script should I run ?Thanks you very much again?

**Comment by shawnzhangyx** [comment]
@liufuyan2016 If I remember correctly, it would give you the list of loops per chromosome. I then run "combine_loops_per_sample.sh" to combine the chromosomes into one file per sample.
