### ISSUE TITLE
cvdc_scripts/di_tads.10k.2M/find_dynamic_boundary_DI_delta.r

### ISSUE THREAD

**Issue by liufuyan2016** [shawnzhangyx/cvdc_scripts#3]
Dear professor,

When I use the scripts in my human HIC, I found the signal which >200 is fewer? (THE CUTOFF 200 IN find_dynamic_boundary_DI_delta.r). Do you think this is normal ?

**Comment by shawnzhangyx** [comment]
Hi Fuyan,

Yes this is normal. 200 was an ad-hoc cutoff that I used for our dataset. The cutoff will change with different sequencing depth. You might want to call the TADs first, and look at the distribution of DI delta around TADs in your data, and find a better cutoff.
