### ISSUE TITLE
di_tads.10k.2M/calc_DI_delta.r

### ISSUE THREAD

**Issue by liufuyan2016** [shawnzhangyx/cvdc_scripts#4]
Dear,
Could you help me explain the following codes means. Thank you!
dat$dist = ceiling((dat$V6-dat$V2)/10000)-5

**Comment by shawnzhangyx** [comment]
Here is an example line of the file (*.DI.overlap.txt): 
chr1    510001  610001  chr1:560001     chr1    530001  540001  2.42283687276256e-05    10000
chr1    510001  610001  chr1:560001     chr1    560001  570001  574.995845793874        10000
Columns 1-3 denote the regions surrounding TAD boundary, column 4 is the TAD boundary. Columns 5-7 is the location and DI of the bin overlapped with TAD boundary (+-50kb). 
V6 is the 6th column, and V2 is the 2nd column. dat$dist is calculating which bin (10k resolution) with respect to the TAD boundary. 

Let me know if this is clear. 

- Yanxiao
